# Generated by Django 5.0 on 2024-01-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salaryinfo",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
