# Generated by Django 5.0 on 2024-01-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="salaryinfo", name="date_saved",),
    ]
