# Generated by Django 5.0 on 2024-01-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_salaryinfo_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="salaryinfo",
            name="employmentType",
            field=models.CharField(default="regular", max_length=100),
        ),
    ]
