# Generated by Django 5.0 on 2024-01-16 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_salaryinfo_date_saved"),
    ]

    operations = [
        migrations.AddField(
            model_name="salaryinfo",
            name="date_saved",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
