# Generated by Django 5.0 on 2024-01-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_rename_contact_number_employee_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
