# Generated by Django 5.0 on 2024-01-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_salaryinfo_date_saved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salaryinfo",
            name="date_saved",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
