# Generated by Django 5.0 on 2024-01-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_employee_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="employee",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
