# Generated by Django 5.0 on 2024-01-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_salaryinfo_date_saved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salaryinfo", old_name="employee", new_name="username",
        ),
    ]
