# Generated by Django 5.0 on 2024-01-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_rename_employee_salaryinfo_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salaryinfo", old_name="username", new_name="employee",
        ),
        migrations.AlterField(
            model_name="salaryinfo",
            name="tax",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
